website:
  title: "Susan Canavan"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: publications.qmd
        text: Publications
      - icon: github
        href: https://github.com/sucanavan
      - icon: mortarboard
        href: https://scholar.google.com/citations?hl=en&user=YzHpPVgAAAAJ