project:
  type: website

website:
  title: "Susan Canavan"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - icon: github
        href: https://github.com/sucanavan
      - icon: mortarboard
        href: https://scholar.google.com/citations?hl=en&user=YzHpPVgAAAAJ

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false