project:
  type: website

website:
  title: "Susan Canavan, PhD"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: research.qmd
        text: Research
      - href: publications.qmd
        text: Publications
      - href: media.qmd
        text: News and Media
    right:
      - icon: github
        href: https://github.com/sucanavan
      - icon: mortarboard
        href: https://scholar.google.com/citations?hl=en&user=YzHpPVgAAAAJ

format:
  html:
    theme: cosmo
    css: styles.css
    page-layout: full
    toc: false
    mainfont: "CMUSerif"