project:
  type: website

website:
  title: "Susan Canavan"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - icon: github
        href: https://github.com/sucanavan

format:
  html:
    theme: cosmo