project:
  type: website

website:
  title: "Susan Canavan, PhD"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: research.qmd
        text: Research
      - href: publications.qmd
        text: Publications
      - href: media.qmd
        text: News
      - href: resources.qmd
        text: Tools
    right:
      - icon: envelope
        href: mailto:sucanavan@gmail.com
      - icon: mortarboard
        href: https://scholar.google.com/citations?hl=en&user=YzHpPVgAAAAJ
      - icon: github
        href: https://github.com/sucanavan
      - text: ResearchGate
        href: https://www.researchgate.net/profile/Susan-Canavan?ev=hdr_xprf

format:
  html:
    theme: cosmo
    css: styles.css
    page-layout: full
    toc: false
    mainfont: CMUSerif